#!/usr/bin/env sh

_() {
  YEAR="1970"
  echo "GitHub Username: "
  read -r USERNAME
  echo "GitHub Access token: "
  read -r ACCESS_TOKEN

  [ -z "$USERNAME" ] && exit 1
  [ -z "$ACCESS_TOKEN" ] && exit 1  
  [ ! -d $YEAR ] && mkdir $YEAR

  cd "${YEAR}" || exit
  git init
  git config user.name "${USERNAME}"
  
  # Fetch GitHub User ID dynamically to format the official noreply email
  USER_ID=$(curl -s -H "Authorization: token $ACCESS_TOKEN" https://api.github.com/user | grep -o '"id": [0-9]*' | cut -d' ' -f2)
  if [ -n "$USER_ID" ]; then
    git config user.email "${USER_ID}+${USERNAME}@users.noreply.github.com"
  else
    git config user.email "${USERNAME}@users.noreply.github.com"
  fi

  echo "**${YEAR}** -Generated by https://github.com/mbahomaid/1970-script My Github sensei" \
    >README.md
  git add .
  GIT_AUTHOR_DATE="${YEAR}-01-01T18:00:00" \
    GIT_COMMITTER_DATE="${YEAR}-01-01T18:00:00" \
    git commit -m "${YEAR}"
  git remote add origin "https://${USERNAME}:${ACCESS_TOKEN}@github.com/${USERNAME}/${YEAR}.git"
  git branch -M main
  git push -u origin main -f
  cd ..
  rm -rf "${YEAR}"

  echo
  echo "Cool, check your profile now: https://github.com/${USERNAME}"
} && _

unset -f _
